# Generated by Django 4.0.2 on 2022-04-15 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('chain_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_word', models.CharField(max_length=13)),
                ('second_word', models.CharField(max_length=13)),
                ('third_word', models.CharField(max_length=13)),
                ('fourth_word', models.CharField(max_length=13)),
                ('fifth_word', models.CharField(max_length=13)),
                ('sixth_word', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Display',
            fields=[
                ('display_id', models.AutoField(primary_key=True, serialize=False)),
                ('visual_mode', models.CharField(max_length=20)),
                ('accessibility', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('difficulty', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('score_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SetView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordchain_app.display')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Selects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordchain_app.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordchain_app.chain')),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordchain_app.score')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiveScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordchain_app.score')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordchain_app.chain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IsAssignedTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordchain_app.chain')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordchain_app.level')),
            ],
        ),
    ]
